language: rust
os:
- windows
- osx
- linux
rust:
- stable
- nightly
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
deploy:
  provider: releases
  api_key:
    secure: Cuhk7KNM4p7umHWhORY+N3m7nGR/BDI/HqL85j+So3JsFKNEicVDFkZJMoiSL4DhgMxLIJZ+cyBUFSeazevleNFW9Y9SQNPaMSKNUxycaNrXfiauVomUi2CdfZbdYNAhrc+PeVwYrxbtQzWPSPlfl7CUFvv3pEfOZHkeBpZ2sI1/4CWAJVkdFweOgo3hGekMl15gC28P7Tk5YvXS/Pf5HBSjd7jCKFSBSDxqqVIivLORFJSgEet9hGq0F/4w/0jb0LkN0/tM0LSx3z2pc0T2ZIPXWFIIEHSucjeTZfK4Y5gfpGQDKsVKPQqQ4UCxEqBB5H0DCmeh+hliJWkvhKDSdKpA3SznTJj9DIACY/TxzQEzxg2+/b91aPHDO9BcYiH/wkAOOk4XoUQ2eHbDFoS/kqMVbmKGLRqhUW4leRMm6yZFDYUApeaJWd7YEiUaN7lO8lbdP4yZBSouCZFVY9isVu664RJpF2T3LgrgXPCHrGNBg7HWl+hfyKZn2MCkKP/iUSFKPG+X8NRQVPh+T9oJzKadVPo7rLoV6TCt0kjejAp7wV7DEMNmRfZacRiVb0TjtvDG/EjG44NXiN5YlYrW93eTwE22bOI8JF2yyXyoZ3ZIvlXZ+ibLTXy85oBn/rL7l0iiaWXgrZiEL7k2/vsLB9YfkdVbesXLoVmNzueB+j0=
  file: target/debug/bone
  on:
    repo: tanis2000/bone
