language: rust
os:
- windows
- osx
- linux
rust:
- stable
- nightly
cache: cargo
script:
- cargo build --verbose --all
- cargo test --verbose --all
- ls -al target/debug/
deploy:
  provider: releases
  api_key:
    secure: T19R2CTVF/+THrh4xT+LxPviVgUh9hw66N2xRkpVbRuY2OU4zyic7J64ajcwZb5luWaG7kNy17qQ7NUP+Msii5elXTo7vZWvDXRkHvoT2j8lxGxzmMppX8xwc2pUmuo9Z+yih6aQvC5KQBMQeyiIwu5QEyhzajzJoeiQ1u4yihzA40AGne1j3OCJ/GsmNRUtOY7ZYQ0JCOTpBXfULw7MgV69u3SEBxFmlMi+moT8xfBbYNKTkCenhdEUcfTGzyicpxvmvzx0lVmP04mHNYusZMlKmn/mFxpR4mbS4yCoNuRYA/vp5l0eTwSGhDvkbZMNf99jTtv+MHVMyP+Qxvw8ZbnnD9KdZ2S45bIOU8ewg3RqCpTLTe8Poy+kyuQxM/a7uvu8OsF5ViAgDzfMp3qFoVec4I74bbDpF3TxhDzv4JLvkvQPFWUqM13Xza3UPUhsbLwjdF523XybhNg58J8LNJ58UCooQ0l5JifzFBYQkLVBlaZCro3iMDy+X4TrdCN17kCHChKSrEaVSS0x2fb99T9Hji/2jgz1qAlH2U4PldCaVo45rQhkWEdbe+RBFwTaA1/Jmm/3rJmdiflMWlTrxMntwDzEIr149fKgMguAbs1GBvBnosBNZITHJ9cGFr4Qbw0/ULXtPTQGZrEf1ID3TVRc2G8fsPX4dP+B0l0QqVY=
  file: target/debug/bone
  skip_cleanup: true
  draft: true
  on:
    repo: tanis2000/bone
