[package]
name = "bone"
version = "0.1.2"
authors = ["Valerio Santinelli <santinelli@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
derive_builder = "0.7.2"
handlebars = "1.1.0"
serde = { version = "1.0.60", features = ["derive"] }
serde_json = "1.0.39"